### ISSUE TITLE
Audiobook jumps after each reboot.

### ISSUE THREAD

**Issue by MedicInMirrorshades** [syntheticpp/juplic#1]
When I'm in the middle of playing a long MP3 and I either shut off my vehicle or pull the power manually first, the MP3 starts playing 1-2 minutes farther than where I had stopped. I've noticed that it's not consistent in how far it jumps ahead, and this may be due to how long the file is- over 7 hours long.
Just wondering if you might have an idea where to look, as it is a bit irritating to have to go into the MPD client every time and adjust it.

**Comment by syntheticpp** [comment]
Current logic is: every 20 seconds the actual playback position is written to the SD card.
So, theoretically, the worst case would be to hear 20s of the audio book again. I wonder how it could jump to a unheard position, and yes, this is annoying in case of a audio book.
I assume mpd writes a wrong position to the SD or restores the position with an different procedure, both is hard to fix at the moment.
But I've updated a new firmware for the RPi 2 which is build with more recent packages (ffmpg, mpg123, ...), maybe this helps.

**Comment by MedicInMirrorshades** [comment]
I see. I've been using it on a RPi 1 512 Mb B (not B+). I wonder if I reimage if it would help... I'll give it a shot. I suppose with that large of an MP3 it's possible to get the MPD client confused, and maybe the time/length isn't totally accurate. In any case, I'll play around with it. Thanks!

**Comment by MedicInMirrorshades** [comment]
After using it consistently and noticing that the MPD client is often stating different lengths of the MP3, I've decided that it must be the client's fault. That said, I haven't had any issues with "part 2" of the audio book, nor have I had problems with any other files. Closing this issue. Thanks for your help!
